version: "3"
services:
  nginx:
    build: ./nginx
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./www/:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/enable-php.conf:/etc/nginx/enable-php.conf
      - ./data/log/:/home/wwwlogs
  phpfpm7.1:
    build: ./phpfpm
    container_name: phpfpm_server
    restart: always
    ports:
      - "9000:9000"
    volumes:
       - ./www/:/var/www/html
       - ./phpfpm/etc/php.ini:/usr/local/etc/php/php.ini
       - ./phpfpm/etc/www.conf:/usr/local/etc/php-fpm.d/www.conf
  mysql:
    build: ./mysql
    container_name: mysql_server
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./data/mysql:/var/lib/mysql
  redis:
    build: ./redis
    container_name: redis_server
    restart: always
    volumes:
      - ./data/redis:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
